# Generated by Django 5.0.1 on 2024-02-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='time when instance is created')),
                ('modifiedAt', models.DateTimeField(auto_now=True, help_text='time when instance is modified')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('paragraph', models.ManyToManyField(related_name='paragraphs', to='posts.paragraph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
